version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./docker_mysql:/docker-entrypoint-initdb.d/
    container_name: "mysql-8"
    networks:
      app_net:
        ipv4_address: 11.11.11.12
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: "rabbitmq"
    networks:
     app_net:
       ipv4_address: 11.11.11.11
  messenger:
    build: .
    restart: always
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - mysql
      - rabbitmq
    container_name: "messenger"
    networks:
      app_net:
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.11.11.0/16
